artifacts_root: artifacts


# data_ingestion:
#   root_dir: artifacts/data_ingestion
#   source_URL: https://github.com/Abdul-Jaweed/Plant-Disease-Classification/blob/68ccec27bbdd574c6ab243613e994696532543b4/sample-data/sample-data.zip
#   local_data_file: artifacts/data_ingestion/data.zip
#   unzip_dir: artifacts/data_ingestion


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Abdul-Jaweed/Plant-Disease-Classification/main/sample-data/sample-data.zip?token=GHSAT0AAAAAAB3M7MGBVESQ4NPO6L3MUOUOZDV2V3A
  #source_URL: https://github.com/Abdul-Jaweed/Plant-Disease-Classification/blob/main/sample-data/sample-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion